### ISSUE TITLE
Rewriting a Fork

### ISSUE THREAD

**Issue by cortner** [cortner/MA3J8ApxThyApp#1]
@JikaiYan --- I hope this reaches you. I am hoping to makes some bigger changes to this repo that include rewriting the history. Would you be willing to temporarily delete your fork? I can ping you here again once the main changes are completed and if you actually want to maintain a fork of this repo.  Thank you.

**Comment by JikaiYan** [comment]
@cortner Hi~ I have deleted it. It would be great if you could ping me again after the changes. Thank you.

**Comment by cortner** [comment]
thank you, I appreciate it.

**Comment by cortner** [comment]
@JikaiYan  - I'll keep editing and making changes, but I don't plan to edit the history anymore.

**Comment by JikaiYan** [comment]
@cortner OK! Thank you for notification.
